version: '3'
services:
  db:
    build: ./postgres
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
volumes:
  postgres_volume:
